export interface Locality {
  name: string
}

export interface Department {
  name: string
  localities: string[]
}

export const URUGUAY_DEPARTMENTS: Department[] = [
  {
    name: 'Artigas',
    localities: [
      'Artigas',
      'Bella Unión',
      'Baltasar Brum',
      'Tomás Gomensoro',
      'Las Piedras',
      'Javier de Viana',
      'Franquia',
      'Coronado',
      'Colonia Palma',
      'Bernabé Rivera',
    ],
  },
  {
    name: 'Canelones',
    localities: [
      'Canelones',
      'Ciudad de la Costa',
      'Las Piedras',
      'Pando',
      'La Paz',
      'Progreso',
      'Santa Lucía',
      'Atlántida',
      'Parque del Plata',
      'Sauce',
      'Toledo',
      'Tala',
      'San Ramón',
      'Joaquín Suárez',
      'Paso Carrasco',
      'Barros Blancos',
      'Empalme Olmos',
      'Montes',
      'Paso de Pache',
      'San Antonio',
      'Salinas',
      'Soca',
      'Santa Rosa',
      'Migues',
      'Estación Tapia',
      'Aguas Corrientes',
      'Los Cerrillos',
      'Nicolich',
      'San Jacinto',
      'Neptunia',
      'Marindia',
      'San Luis',
      'Lagomar',
      'Solymar',
      'Shangrilá',
      'El Pinar',
      'Salinas',
    ],
  },
  {
    name: 'Cerro Largo',
    localities: [
      'Melo',
      'Río Branco',
      'Fraile Muerto',
      'Isidoro Noblía',
      'Aceguá',
      'Tupambaé',
      'Placido Rosas',
      'Ramón Trigo',
      'Tres Islas',
      'Arbolito',
    ],
  },
  {
    name: 'Colonia',
    localities: [
      'Colonia del Sacramento',
      'Carmelo',
      'Juan Lacaze',
      'Nueva Helvecia',
      'Rosario',
      'Tarariras',
      'Ombúes de Lavalle',
      'Nueva Palmira',
      'Colonia Valdense',
      'Florencio Sánchez',
      'Conchillas',
      'Miguelete',
      'La Paz',
      'Cerro',
      'Estación Colonia',
    ],
  },
  {
    name: 'Durazno',
    localities: [
      'Durazno',
      'Sarandí del Yi',
      'Villa del Carmen',
      'La Paloma',
      'Carlos Reyles',
      'Blanquillo',
      'Centenario',
      'San Jorge',
    ],
  },
  {
    name: 'Flores',
    localities: [
      'Trinidad',
      'Ismael Cortinas',
      'Andresito',
    ],
  },
  {
    name: 'Florida',
    localities: [
      'Florida',
      'Sarandí Grande',
      'Fray Marcos',
      'Casupá',
      'Cardal',
      'Independencia',
      'Veinticinco de Agosto',
      'Chamizo',
      'Cerro Colorado',
      'Mendoza Grande',
      'Nico Pérez',
      'Cerro Chato',
      'Illescas',
    ],
  },
  {
    name: 'Lavalleja',
    localities: [
      'Minas',
      'José Pedro Varela',
      'Solís de Mataojo',
      'Mariscala',
      'Zapicán',
      'Pirarajá',
      'Villa Serrana',
      'Illescas',
    ],
  },
  {
    name: 'Maldonado',
    localities: [
      'Maldonado',
      'Punta del Este',
      'San Carlos',
      'Piriápolis',
      'Pan de Azúcar',
      'Aiguá',
      'Garzón',
      'Playa Grande',
      'La Barra',
      'José Ignacio',
      'Manantiales',
      'Laguna del Sauce',
      'Balneario Buenos Aires',
      'Eden Rock',
      'Playa Verde',
      'Ocean Park',
      'Solís',
      'Gregorio Aznárez',
    ],
  },
  {
    name: 'Montevideo',
    localities: [
      'Montevideo',
      'Ciudad Vieja',
      'Centro',
      'Barrio Sur',
      'Cordón',
      'Palermo',
      'Parque Rodó',
      'Tres Cruces',
      'La Comercial',
      'Larrañaga',
      'La Blanqueada',
      'Pocitos',
      'Punta Carretas',
      'Parque Batlle',
      'Malvín',
      'Buceo',
      'Carrasco',
      'Punta Gorda',
      'Unión',
      'Villa Española',
      'Reducto',
      'Capurro',
      'Bella Vista',
      'Aguada',
      'Paso Molino',
      'Belvedere',
      'La Teja',
      'Prado',
      'Nuevo París',
      'Cerro',
      'Casabó',
      'Pajas Blancas',
      'Colón',
      'Lezica',
      'Manga',
      'Piedras Blancas',
      'Jardines del Hipódromo',
      'Ituzaingó',
      'Flor de Maroñas',
      'Maroñas',
      'Villa García',
      'Bañados de Carrasco',
      'Carrasco Norte',
    ],
  },
  {
    name: 'Paysandú',
    localities: [
      'Paysandú',
      'Guichón',
      'Quebracho',
      'Porvenir',
      'Lorenzo Geyres',
      'Piedras Coloradas',
      'San Félix',
      'Tambores',
      'Cerro Chato',
      'Casa Blanca',
      'Chapicuy',
      'Constancia',
      'Esperanza',
      'Gallinal',
      'Merinos',
      'Orgoroso',
      'Piñera',
    ],
  },
  {
    name: 'Río Negro',
    localities: [
      'Fray Bentos',
      'Young',
      'San Javier',
      'Nuevo Berlín',
      'Villa Soriano',
      'Grecco',
      'Algorta',
      'Sarandí de Navarro',
      'Las Cañas',
    ],
  },
  {
    name: 'Rivera',
    localities: [
      'Rivera',
      'Tranqueras',
      'Vichadero',
      'Minas de Corrales',
      'Masoller',
      'Amarillo',
      'Cerrillada',
      'La Puente',
      'Lapuente',
      'Mandubí',
      'Moirones',
    ],
  },
  {
    name: 'Rocha',
    localities: [
      'Rocha',
      'Chuy',
      'Lascano',
      'Castillos',
      'La Paloma',
      'La Pedrera',
      'Cabo Polonio',
      'Punta del Diablo',
      'Valizas',
      'Aguas Dulces',
      'Barra de Valizas',
      'La Esmeralda',
      'Oceanía del Polonio',
      'Punta Rubia',
      'San Luis al Medio',
      'Velázquez',
      '18 de Julio',
      'Cebollatí',
    ],
  },
  {
    name: 'Salto',
    localities: [
      'Salto',
      'Constitución',
      'Belén',
      'Termas del Daymán',
      'Termas del Arapey',
      'Villa Constitución',
      'Biassini',
      'Fernández',
      'Mataojo',
      'Puntas de Valentín',
      'Pueblo Cayetano',
      'Pueblo Lavalleja',
      'Rincón de Valentín',
      'San Antonio',
    ],
  },
  {
    name: 'San José',
    localities: [
      'San José de Mayo',
      'Ciudad del Plata',
      'Libertad',
      'Ecilda Paullier',
      'Rafael Perazza',
      'Rodríguez',
      'Delta del Tigre',
      'Puntas de Valdez',
      'Villa María',
      'Raigón',
      'Kiyú',
      'Rincón de la Bolsa',
      'Boca del Cufré',
      'Capurro',
      'Carreta Quemada',
      'Ituzaingó',
      'Mal Abrigo',
      'Mangrullo',
      'Monte Grande',
      'Safici',
    ],
  },
  {
    name: 'Soriano',
    localities: [
      'Mercedes',
      'Dolores',
      'Cardona',
      'José Enrique Rodó',
      'Palmitas',
      'Villa Soriano',
      'Egaña',
      'Santa Catalina',
      'Risso',
      'Sacachispas',
      'Chacras de Dolores',
      'Cañada Nieto',
      'Palo Solo',
      'Castillos',
    ],
  },
  {
    name: 'Tacuarembó',
    localities: [
      'Tacuarembó',
      'Paso de los Toros',
      'San Gregorio de Polanco',
      'Ansina',
      'Curtina',
      'Villa Ansina',
      'Achar',
      'Tambores',
      'Laureles',
      'Paso Bonilla',
      'Piedra Sola',
      'Clara',
      'La Hilera',
    ],
  },
  {
    name: 'Treinta y Tres',
    localities: [
      'Treinta y Tres',
      'Vergara',
      'Santa Clara de Olimar',
      'Cerro Chato',
      'Villa Sara',
      'Ejido de Treinta y Tres',
      'General Enrique Martínez',
      'Rincón',
      'Mendizábal',
      'María Albina',
      'Arrozal Treinta y Tres',
    ],
  },
]

export const getDepartmentNames = (): string[] => {
  return URUGUAY_DEPARTMENTS.map((dept) => dept.name).sort()
}

export const getLocalitiesByDepartment = (departmentName: string): string[] => {
  const department = URUGUAY_DEPARTMENTS.find((dept) => dept.name === departmentName)
  return department ? department.localities.sort() : []
}
